feat: update to show installation requirements
ionic-team/capacitor-google-maps pull request #47
Opened 2024-09-23 17:45 UTC by dtarnawsky

This adds the missing requirements for minimum iOS deployment target of 14.0 and the skipLibCheck property in TSConfig.

2024-09-24 10:37 UTC, jcesarmobile requested changes
The original file is the one inside plugin folder, then it gets copied into the root if running `npm run build`.
https://github.com/ionic-team/capacitor-google-maps/blob/main/plugin/README.md

The deployment target should also be changed in the project, not just in the Podfile, the text might look like this 
https://capacitorjs.com/docs/v5/updating/4-0#raise-ios-deployment-target

2024-09-24 14:18 UTC, dtarnawsky commented
It says:

> Additionally, you will need to open your project in XCode and set the `iOS Deployment Target` to `iOS 14.0` or higher in the `Build Settings` tab.

2024-09-24 15:04 UTC, jcesarmobile commented
Yeah, that's incomplete or unclear, you have to change it for both the project and all the targets, each one of them have a `Build settings` tab with independent deployment target values and has to be changed for all.

<img width="157" alt="Captura de pantalla 2024-09-24 a las 17 03 12" src="https://github.com/user-attachments/assets/b27be9d0-41de-4f24-b854-54bdb92fa3a5">

2024-09-24 15:28 UTC, dtarnawsky commented
I've cleaned up the wording to specify that you need to do it for the target app. The projects deployment target doesnt need to be updated (see this [sample app](https://github.com/dtarnawsky/cs-google-maps))

2024-09-24 16:04 UTC, jcesarmobile requested changes
Despite the app might build with different deployment targets on the project and the targets, it can cause issues, so it's better to always have the versions in sync.

The new text is incorrect, it should say in the opposite order, like 
> select `Targets` > `App` (or the name of your target) and in the `Build Settings` tab
Users could have more than a target, so that's why I'm asking to use the same text we have on the migrate guide, and also for consistency

2024-09-24 17:19 UTC, dtarnawsky commented
Ok, changed again.

2024-09-24 17:38 UTC, jcesarmobile commented on plugin/README.md
> +Additionally, you will need to open your project in XCode and in the `Build Settings` tab for your `Project` and for each `Target` set the `iOS Deployment Target` to `iOS 14` or higher.
```suggestion
Additionally, you will need to open your project in XCode and in the `Build Settings` tab for your `Project` and for each `Target` set the `iOS Deployment Target` to `iOS 14.0` or higher.
```
Adding the `.0` as `14` is not a valid value

2024-09-25 09:17 UTC, jcesarmobile approved these changes

2024-09-25 13:30 UTC, merged